### ISSUE TITLE
Plugin Doesn't Exists on Wordpress.org?

### ISSUE THREAD

**Issue by 0Neji** [jcchavezs/cmb2-conditionals#3]
Just looking at using this plugin as it looks like exactly what I need. The link in your readme doesn't lead anywhere however - neither does it come up via searching.

Not a big deal, I can grab it from here but thought you'd might like to know.

**Comment by jcchavezs** [comment]
Thanks for the feedback. I have been discussing it with Wordpress, they do not allow me to use cmb2-conditionals as slug because I am not part of the [CMB2](https://github.com/WebDevStudios/CMB2) team. These days have been crazy as I am moving from Norway to Spain but as soon as I manage to stablish my self there I will pick issues in CMB2 so I become "part of the team" and after that I can publish my plugin using the cmb2-conditionals slug.

**Comment by 0Neji** [comment]
Ahh, I see. Thanks for the udpate!

Nice work on the plugin by the way - working perfectly!
